# Generated by Django 4.2.8 on 2024-03-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seller_images/"
                    ),
                ),
                ("phone", models.IntegerField()),
                ("address", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
