# Generated by Django 4.2.8 on 2024-03-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="address",
            field=models.CharField(max_length=255),
        ),
    ]
