# Generated by Django 5.0.3 on 2024-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0008_viewhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_start", models.DateTimeField(auto_now_add=True)),
                ("date_end", models.DateTimeField()),
                ("promocode", models.CharField(max_length=255)),
                ("is_group", models.BooleanField(default=False)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("type", models.CharField(max_length=255)),
                ("products", models.ManyToManyField(to="shopapp.product")),
            ],
        ),
    ]
