# Generated by Django 5.0.3 on 2024-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0009_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
