# Generated by Django 5.0.3 on 2024-03-25 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shopapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0010_discount_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=shopapp.models.avatar_directory_path,
                    ),
                ),
                ("phone", models.IntegerField()),
                ("middle_name", models.CharField(max_length=255)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shopapp.seller"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
