# Generated by Django 5.0.3 on 2024-03-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0011_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="content",
        ),
        migrations.AddField(
            model_name="productseller",
            name="sale",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.product",
            ),
        ),
    ]
