# Generated by Django 5.0.3 on 2024-03-31 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0011_profile"),
        (
            "shopapp",
            "0012_rename_description_review_content_productseller_sale_and_more",
        ),
    ]

    operations = []
