# Generated by Django 4.1 on 2024-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0013_merge_20240331_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
