# Generated by Django 5.0.3 on 2024-04-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0014_discount_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="type",
            field=models.CharField(
                choices=[("%", "%"), ("RUB", "RUB")], default="%", max_length=100
            ),
        ),
    ]
