# Generated by Django 5.0.3 on 2024-04-14 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0014_discount_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viewhistory",
            name="viewed_products",
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="view_historys",
                to="shopapp.product",
            ),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="view_historys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
