# Generated by Django 5.0.3 on 2024-04-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0015_remove_viewhistory_viewed_products_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewhistory",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
