# Generated by Django 5.0.3 on 2024-04-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0015_alter_discount_type"),
        ("shopapp", "0016_alter_viewhistory_user"),
    ]

    operations = []
