# Generated by Django 5.0.3 on 2024-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0017_merge_20240419_0611"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="is_displayed",
            field=models.BooleanField(default=False),
        ),
    ]
