# Generated by Django 5.0.3 on 2024-04-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0019_alter_viewhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="categories",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="categories",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="shopapp.categories",
            ),
        ),
    ]
