# Generated by Django 5.0.3 on 2024-04-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0019_alter_viewhistory_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="is_displayed",
            new_name="is_active",
        ),
    ]
