# Generated by Django 5.0.3 on 2024-04-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0015_rename_features_product_details"),
        ("shopapp", "0019_alter_viewhistory_user"),
    ]

    operations = []
