# Generated by Django 5.0.3 on 2024-04-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0020_merge_20240423_1741"),
        ("shopapp", "0020_rename_is_displayed_discount_is_active"),
    ]

    operations = []
