# Generated by Django 5.0.3 on 2024-04-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0017_alter_product_category"),
        ("shopapp", "0021_merge_20240423_1958"),
    ]

    operations = []
