# Generated by Django 5.0.3 on 2024-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0022_merge_20240424_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.JSONField(default=dict),
        ),
    ]
