# Generated by Django 5.0.3 on 2024-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0022_merge_20240424_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="address_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="address_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="description_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="description_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="email_en",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="email_ru",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="image_en",
            field=models.ImageField(
                blank=True, null=True, upload_to="seller_image_directory_path"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="image_ru",
            field=models.ImageField(
                blank=True, null=True, upload_to="seller_image_directory_path"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="phone_en",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="phone_ru",
            field=models.IntegerField(null=True),
        ),
    ]
