# Generated by Django 5.0.3 on 2024-05-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0024_alter_product_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productseller",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_sellers",
                to="shopapp.product",
            ),
        ),
    ]
