# Generated by Django 5.0.3 on 2024-05-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0023_seller_address_en_seller_address_ru_and_more"),
        ("shopapp", "0025_alter_productseller_product"),
    ]

    operations = []
