# Generated by Django 5.0.3 on 2024-05-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0020_categories_archived_categories_name_and_more"),
        ("shopapp", "0026_alter_product_category_alter_viewhistory_user"),
    ]

    operations = []
