# Generated by Django 5.0.3 on 2024-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0026_alter_product_category_alter_viewhistory_user"),
        ("shopapp", "0027_alter_seller_options_remove_seller_address_en_and_more"),
    ]

    operations = []
