# Generated by Django 5.0.3 on 2024-05-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0027_merge_20240506_1718"),
        ("shopapp", "0028_alter_productseller_product"),
    ]

    operations = []
