# Generated by Django 5.0.3 on 2024-05-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0028_merge_20240505_1058"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "discount", "verbose_name_plural": "discounts"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "product_image",
                "verbose_name_plural": "product_images",
            },
        ),
        migrations.AlterModelOptions(
            name="productseller",
            options={
                "verbose_name": "product_seller",
                "verbose_name_plural": "product_sellers",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "profile", "verbose_name_plural": "profiles"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "review", "verbose_name_plural": "reviews"},
        ),
        migrations.AlterModelOptions(
            name="seller",
            options={"verbose_name": "seller", "verbose_name_plural": "sellers"},
        ),
        migrations.AlterModelOptions(
            name="viewhistory",
            options={
                "verbose_name": "view_history",
                "verbose_name_plural": "view_histories",
            },
        ),
        migrations.AlterField(
            model_name="categories",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="date_end",
            field=models.DateTimeField(verbose_name="date_end"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="date_start",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date_start"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.discount_img_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="is_group"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="products",
            field=models.ManyToManyField(to="shopapp.product", verbose_name="products"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="promocode",
            field=models.CharField(max_length=255, verbose_name="promocode"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="value"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="archived"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_category",
                to="shopapp.categories",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.JSONField(blank=True, default=dict, verbose_name="details"),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shopapp.productimage",
                verbose_name="images",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shopapp.productimage",
                verbose_name="preview",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=shopapp.models.product_images_directory_path,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_preview",
            field=models.BooleanField(default=False, verbose_name="is_preview"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_sellers",
                to="shopapp.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="quantity",
            field=models.SmallIntegerField(default=0, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="sale",
            field=models.IntegerField(blank=True, default=0, verbose_name="sale"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="seller",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.avatar_directory_path,
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(max_length=255, verbose_name="middle_name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="seller",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_reviews",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created_reviews"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews_product",
                to="shopapp.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation_date"),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="view_historys",
                to="shopapp.product",
                verbose_name="creation_date",
            ),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
