# Generated by Django 5.0.3 on 2024-05-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0029_alter_categories_options_alter_discount_options_and_more"),
        ("shopapp", "0029_merge_20240510_1757"),
    ]

    operations = []
