# Generated by Django 5.0.3 on 2024-05-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0029_merge_20240510_1757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
            ),
        ),
    ]
