# Generated by Django 5.0.3 on 2024-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0030_alter_profile_middle_name_alter_profile_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
