# Generated by Django 5.0.3 on 2024-05-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0030_merge_20240512_0726"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "категорию", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={"verbose_name": "скидку", "verbose_name_plural": "Скидки"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "продукт-картинку",
                "verbose_name_plural": "Продукты-картинки",
            },
        ),
        migrations.AlterModelOptions(
            name="productseller",
            options={
                "verbose_name": "продукт-продавца",
                "verbose_name_plural": "Продукты-продавцы",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="seller",
            options={"verbose_name": "продавца", "verbose_name_plural": "Продавцы"},
        ),
        migrations.AlterModelOptions(
            name="viewhistory",
            options={
                "verbose_name": "просмотр истории",
                "verbose_name_plural": "Просмотр историй",
            },
        ),
        migrations.RemoveField(
            model_name="categories",
            name="parent",
        ),
        migrations.AlterField(
            model_name="categories",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="архивирован"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="date_end",
            field=models.DateTimeField(verbose_name="дата конца"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="date_start",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата начала"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.discount_img_directory_path,
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активная"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="группа"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="name",
            field=models.CharField(max_length=255, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="products",
            field=models.ManyToManyField(to="shopapp.product", verbose_name="продукты"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="promocode",
            field=models.CharField(max_length=255, verbose_name="промокод"),
        ),
        migrations.AlterField(
            model_name="discount",
            name="type",
            field=models.CharField(
                choices=[("%", "%"), ("RUB", "RUB")],
                default="%",
                max_length=100,
                verbose_name="тип",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="значение"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="архивирован"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_category",
                to="shopapp.categories",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.JSONField(blank=True, default=dict, verbose_name="детали"),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shopapp.productimage",
                verbose_name="картинки",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shopapp.productimage",
                verbose_name="предпросмотр",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=shopapp.models.product_images_directory_path,
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_preview",
            field=models.BooleanField(default=False, verbose_name="предпросмотр"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="цена"
            ),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_sellers",
                to="shopapp.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="quantity",
            field=models.SmallIntegerField(default=0, verbose_name="количество"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="sale",
            field=models.IntegerField(blank=True, default=0, verbose_name="скидка"),
        ),
        migrations.AlterField(
            model_name="productseller",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="продавец",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.avatar_directory_path,
                verbose_name="аватар",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(max_length=255, verbose_name="отчество"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(verbose_name="номер телефона"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="продавец",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, verbose_name="содержание"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_reviews",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="созданные отзывы"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews_product",
                to="shopapp.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="address",
            field=models.CharField(max_length=255, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="description",
            field=models.CharField(max_length=255, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seller_image_directory_path",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="name",
            field=models.CharField(max_length=255, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="seller",
            name="phone",
            field=models.IntegerField(verbose_name="номер телефона"),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="дата создания"),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="view_historys",
                to="shopapp.product",
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="viewhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
