# Generated by Django 5.0.3 on 2024-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0030_alter_profile_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
