# Generated by Django 5.0.3 on 2024-05-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0031_alter_profile_middle_name_alter_profile_phone"),
        ("shopapp", "0032_alter_profile_phone"),
    ]

    operations = []
