# Generated by Django 5.0.3 on 2024-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0031_alter_categories_options_alter_discount_options_and_more"),
        ("shopapp", "0033_merge_20240520_1605"),
    ]

    operations = []
