# Generated by Django 5.0.3 on 2024-05-22 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0034_merge_20240522_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(max_length=255, verbose_name="отчество"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.IntegerField(verbose_name="номер телефона"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="продавец",
            ),
            preserve_default=False,
        ),
    ]
