# Generated by Django 5.0.3 on 2024-05-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0034_alter_profile_phone"),
        ("shopapp", "0035_alter_profile_middle_name_alter_profile_phone_and_more"),
    ]

    operations = []
