# Generated by Django 5.0.3 on 2024-05-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0037_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategories",
                to="shopapp.categories",
            ),
        ),
    ]
