# Generated by Django 5.0.3 on 2024-05-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0035_product_created_at"),
        ("shopapp", "0038_categories_parent"),
    ]

    operations = []
