# Generated by Django 5.0.3 on 2024-05-26 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0039_merge_0035_product_created_at_0038_categories_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shopapp.seller",
                verbose_name="продавец",
            ),
        ),
    ]
