# Generated by Django 5.0.3 on 2024-05-26 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0041_alter_profile_middle_name_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\+(\\d){1,3} \\((\\d){2,3}\\) (\\d{3}) (\\d{2}) (\\d){2}$",
                        message="Введите правильный номер. Пример: +7 (999) 999 99 99",
                    )
                ],
            ),
        ),
    ]
