# Generated by Django 5.0.3 on 2024-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0042_alter_profile_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("image", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("is_big", models.BooleanField(default=False)),
            ],
        ),
    ]
