# Generated by Django 5.0.3 on 2024-05-29 13:18

from django.db import migrations, models

import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0043_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.banner_image_directory_path,
            ),
        ),
    ]
