# Generated by Django 5.0.3 on 2024-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="имя"),
        ),
    ]
