# Generated by Django 5.0.3 on 2024-03-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="is_boolean",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="value",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cache_time",
            field=models.IntegerField(default=5),
        ),
    ]
