# Generated by Django 5.0.3 on 2024-04-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0001_initial"),
        ("shopapp", "0013_merge_20240331_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="shopapp.productseller",
            ),
        ),
    ]
