# Generated by Django 5.0.3 on 2024-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference_num",
            field=models.CharField(default="AAA22", max_length=100),
            preserve_default=False,
        ),
    ]
