# Generated by Django 5.0.3 on 2024-04-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0005_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                default="cancelled",
                max_length=100,
            ),
        ),
    ]
