# Generated by Django 5.0.3 on 2024-05-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0008_transaction"),
        ("shopapp", "0029_alter_categories_options_alter_discount_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": "created_at",
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "order_item",
                "verbose_name_plural": "order_items",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(max_length=200, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="reference_num",
            field=models.CharField(max_length=100, verbose_name="reference_num"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.IntegerField(verbose_name="count"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="old_price",
            field=models.FloatField(verbose_name="old_price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="shopapp.productseller",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="pay.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                default="cancelled",
                max_length=100,
                verbose_name="payment_status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.CharField(max_length=100, verbose_name="uuid"),
        ),
    ]
