# Generated by Django 5.0.3 on 2024-05-12 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0009_alter_order_options_alter_orderitem_options_and_more"),
        ("shopapp", "0031_alter_categories_options_alter_discount_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": "created_at",
                "verbose_name": "заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "заказ-товар",
                "verbose_name_plural": "Заказы-товары",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "транзакцию", "verbose_name_plural": "Транзакции"},
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=100, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, verbose_name="город"),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(max_length=200, verbose_name="комментарий"),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создан"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.CharField(
                choices=[("pickup", "Самовывоз"), ("courier", "Курьером")],
                default="pickup",
                max_length=100,
                verbose_name="доставка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("credit_card", "Кредитная карта")],
                default="cash",
                max_length=100,
                verbose_name="оплата",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Олачено"), ("cancelled", "Отменен")],
                default="cancelled",
                max_length=100,
                verbose_name="статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reference_num",
            field=models.CharField(max_length=100, verbose_name="номер заказа"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.IntegerField(verbose_name="количество"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="old_price",
            field=models.FloatField(verbose_name="старая цена"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="pay.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="shopapp.productseller",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="сумма"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="pay.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Олачено"), ("cancelled", "Отменен")],
                default="cancelled",
                max_length=100,
                verbose_name="статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
