# Generated by Django 5.0.3 on 2024-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0010_alter_order_user_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="reference_num",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
