# Generated by Django 5.0.3 on 2024-05-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0010_alter_order_options_alter_orderitem_options_and_more"),
        ("pay", "0010_remove_order_payment_order_payment_type_and_more"),
        ("pay", "0011_alter_order_address_alter_order_city_and_more"),
    ]

    operations = []
