# Generated by Django 5.0.3 on 2024-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0012_merge_20240530_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Cash"), ("credit_card", "Credit card")],
                default="cash",
                max_length=100,
                verbose_name="оплата",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("courier", "Courier")],
                default="pickup",
                max_length=100,
                verbose_name="доставка",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                default="cancelled",
                max_length=100,
                verbose_name="статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                default="cancelled",
                max_length=100,
                verbose_name="статус оплаты",
            ),
        ),
    ]
