# Generated by Django 5.0.3 on 2024-05-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0013_remove_order_payment_order_payment_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
    ]
